import { createHash } from "node:crypto";
import { cp, lstat, mkdir, readFile, readdir, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { artifactManifestFileName, verifyArtifactManifest } from "./artifactIntegrity.mjs";

export const releaseEnvelopeFileName = "release-envelope.json";
export const pagesProjectName = "smart-portfolio";
export const pagesDomain = "smart-portfolio-bds.pages.dev";

const sha256Pattern = /^[a-f0-9]{64}$/;
const gitShaPattern = /^[a-f0-9]{40}$/;
const generatedRoutesDescription = "Generated by wrangler@4.131.0";
const requiredRouteIncludes = ["/api/contact", "/api/contact/verify"];
const requiredVariableNames = [
  "CONTACT_ALLOWED_ORIGINS",
  "CONTACT_FROM_EMAIL",
  "CONTACT_REPLY_TO_EMAIL",
  "TURNSTILE_ALLOWED_HOSTNAMES"
];

const deploymentTargets = {
  production: {
    branch: "main",
    d1: {
      binding: "CONTACT_RATE_LIMIT_DB",
      databaseName: "smart-portfolio-contact-rate-limit-production",
      databaseId: "8ae31be3-092e-4a86-86ed-c0729f27c61c",
      migrationsDirectory: "migrations"
    },
    vars: {
      TURNSTILE_ALLOWED_HOSTNAMES: "smart-portfolio-bds.pages.dev,nicolasmgioanni.dev,www.nicolasmgioanni.dev",
      CONTACT_ALLOWED_ORIGINS: "https://smart-portfolio-bds.pages.dev,https://nicolasmgioanni.dev,https://www.nicolasmgioanni.dev",
      CONTACT_FROM_EMAIL: "Nicolas Gioanni <noreply@mail.nicolasmgioanni.dev>",
      CONTACT_REPLY_TO_EMAIL: "ngioanni@uw.edu"
    }
  },
  preview: {
    branch: "develop",
    d1: {
      binding: "CONTACT_RATE_LIMIT_DB",
      databaseName: "smart-portfolio-contact-rate-limit-preview",
      databaseId: "963d761b-6055-4adb-9ac8-0bd8f14efad4",
      migrationsDirectory: "migrations"
    },
    vars: {
      TURNSTILE_ALLOWED_HOSTNAMES: "develop.smart-portfolio-bds.pages.dev",
      CONTACT_ALLOWED_ORIGINS: "https://develop.smart-portfolio-bds.pages.dev",
      CONTACT_FROM_EMAIL: "Nicolas Gioanni <noreply@mail.nicolasmgioanni.dev>",
      CONTACT_REPLY_TO_EMAIL: "ngioanni@uw.edu"
    }
  }
};

function sha256(value) {
  return createHash("sha256").update(value).digest("hex");
}

function canonicalize(value) {
  if (Array.isArray(value)) return value.map(canonicalize);
  if (value && typeof value === "object") {
    return Object.fromEntries(Object.keys(value).sort().map((key) => [key, canonicalize(value[key])]));
  }
  return value;
}

function canonicalJson(value) {
  return JSON.stringify(canonicalize(value));
}

function expectExactKeys(value, keys, label) {
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    throw new Error(`${label} must be an object`);
  }
  const actual = Object.keys(value).sort();
  const expected = [...keys].sort();
  if (actual.length !== expected.length || actual.some((key, index) => key !== expected[index])) {
    throw new Error(`${label} must contain exactly ${expected.join(", ")}`);
  }
}

function targetDefinition(target) {
  const definition = deploymentTargets[target];
  if (!definition) throw new Error("Deployment target must be production or preview");
  return definition;
}

function validateVariables(value, expected, label) {
  expectExactKeys(value, requiredVariableNames, label);
  for (const name of requiredVariableNames) {
    if (value[name] !== expected[name]) throw new Error(`${label}.${name} does not match the reviewed deployment value`);
  }
  return Object.fromEntries(requiredVariableNames.map((name) => [name, value[name]]));
}

function findBinding(bindings, label) {
  if (!Array.isArray(bindings) || bindings.length !== 1) {
    throw new Error(`${label} must contain exactly one D1 binding`);
  }
  const binding = bindings[0];
  if (!binding || typeof binding !== "object" || Array.isArray(binding)) {
    throw new Error(`${label} contains an invalid D1 binding`);
  }
  return binding;
}

function validateD1Binding(binding, expected, label, { requireLocalPreviewId }) {
  const expectedKeys = requireLocalPreviewId
    ? ["binding", "database_id", "database_name", "migrations_dir", "preview_database_id"]
    : ["binding", "database_id", "database_name", "migrations_dir"];
  expectExactKeys(binding, expectedKeys, label);
  if (binding.binding !== expected.binding) throw new Error(`${label}.binding is not ${expected.binding}`);
  if (binding.database_name !== expected.databaseName) throw new Error(`${label}.database_name does not match the target`);
  if (binding.database_id !== expected.databaseId) throw new Error(`${label}.database_id does not match the target`);
  if (binding.migrations_dir !== expected.migrationsDirectory) {
    throw new Error(`${label}.migrations_dir does not match the sealed migration directory`);
  }
  if (requireLocalPreviewId && binding.preview_database_id !== "contact-rate-limit-local") {
    throw new Error(`${label}.preview_database_id must keep the reviewed local D1 identifier`);
  }
  return {
    binding: binding.binding,
    databaseName: binding.database_name,
    databaseId: binding.database_id,
    migrationsDirectory: binding.migrations_dir
  };
}

async function readConfig(configPath) {
  const source = await readFile(configPath, "utf8");
  let config;
  try {
    config = JSON.parse(source);
  } catch {
    throw new Error("wrangler.jsonc must remain strict JSON so the release envelope can seal it");
  }
  return { config, source };
}

export async function readSealedRuntimeConfiguration({ configPath, target }) {
  const definition = targetDefinition(target);
  const { config, source } = await readConfig(configPath);
  expectExactKeys(
    config,
    ["$schema", "compatibility_date", "d1_databases", "env", "name", "pages_build_output_dir", "vars"],
    "wrangler.jsonc"
  );
  if (config.name !== pagesProjectName) throw new Error("wrangler.jsonc does not name the reviewed Pages project");
  if (config.pages_build_output_dir !== "./out") throw new Error("wrangler.jsonc must use the reviewed Pages output directory");
  if (config.compatibility_date !== "2026-08-27") throw new Error("wrangler.jsonc compatibility date does not match the reviewed release configuration");
  if (typeof config.$schema !== "string" || !config.$schema.startsWith("https://raw.githubusercontent.com/cloudflare/")) {
    throw new Error("wrangler.jsonc must retain its reviewed Cloudflare schema");
  }
  expectExactKeys(config.env, ["preview"], "wrangler.jsonc.env");
  expectExactKeys(config.env.preview, ["d1_databases", "vars"], "wrangler.jsonc.env.preview");

  const productionBinding = validateD1Binding(
    findBinding(config.d1_databases, "wrangler.jsonc.d1_databases"),
    deploymentTargets.production.d1,
    "wrangler.jsonc.d1_databases[0]",
    { requireLocalPreviewId: true }
  );
  const previewBinding = validateD1Binding(
    findBinding(config.env.preview.d1_databases, "wrangler.jsonc.env.preview.d1_databases"),
    deploymentTargets.preview.d1,
    "wrangler.jsonc.env.preview.d1_databases[0]",
    { requireLocalPreviewId: false }
  );
  const productionVars = validateVariables(config.vars, deploymentTargets.production.vars, "wrangler.jsonc.vars");
  const previewVars = validateVariables(config.env.preview.vars, deploymentTargets.preview.vars, "wrangler.jsonc.env.preview.vars");

  return {
    sourceSha256: sha256(source),
    pages: { projectName: pagesProjectName, domain: pagesDomain, branch: definition.branch },
    target,
    d1: target === "production" ? productionBinding : previewBinding,
    vars: target === "production" ? productionVars : previewVars
  };
}

async function readMigrations(migrationsDirectory) {
  const entries = await readdir(migrationsDirectory, { withFileTypes: true });
  const files = [];
  for (const entry of entries.sort((left, right) => left.name.localeCompare(right.name))) {
    if (entry.isSymbolicLink() || !entry.isFile() || !/^\d{4}_[a-z0-9_]+\.sql$/.test(entry.name)) {
      throw new Error(`Migration directory contains an unsupported entry: ${entry.name}`);
    }
    const contents = await readFile(path.join(migrationsDirectory, entry.name));
    files.push({ path: entry.name, sha256: sha256(contents), size: contents.byteLength });
  }
  if (files.length === 0) throw new Error("Release migrations must not be empty");
  return files;
}

function normalizeRoutes(value) {
  expectExactKeys(value, ["description", "exclude", "include", "version"], "Compiled _routes.json");
  if (value.version !== 1 || value.description !== generatedRoutesDescription) {
    throw new Error("Compiled _routes.json does not come from the locked Wrangler release");
  }
  if (!Array.isArray(value.include) || !Array.isArray(value.exclude)) {
    throw new Error("Compiled _routes.json contains invalid route lists");
  }
  if (canonicalJson(value.include) !== canonicalJson(requiredRouteIncludes) || value.exclude.length !== 0) {
    throw new Error("Compiled _routes.json must route only the reviewed contact endpoints");
  }
  return {
    version: value.version,
    description: value.description,
    include: value.include,
    exclude: value.exclude
  };
}

async function readCompiledFunctions(artifactDirectory, manifest) {
  const workerPath = path.join(artifactDirectory, "_worker.js");
  const workerStats = await lstat(workerPath).catch(() => undefined);
  if (!workerStats?.isDirectory()) throw new Error("Verified artifact is missing the compiled out/_worker.js directory");
  const workerFiles = manifest.files.filter((file) => file.path.startsWith("_worker.js/"));
  if (workerFiles.length === 0 || !workerFiles.some((file) => file.path === "_worker.js/index.js")) {
    throw new Error("Verified artifact is missing the compiled Worker entrypoint");
  }
  const routesPath = path.join(artifactDirectory, "_routes.json");
  let routes;
  try {
    routes = normalizeRoutes(JSON.parse(await readFile(routesPath, "utf8")));
  } catch (error) {
    if (error instanceof SyntaxError) throw new Error("Compiled _routes.json is not valid JSON");
    throw error;
  }
  return { workerDirectory: "_worker.js", files: workerFiles, routes };
}

function unsignedEnvelope({ candidateSha, target, staticArtifact, compiledFunctions, runtimeConfiguration, migrations }) {
  return {
    schemaVersion: 1,
    algorithm: "sha256",
    candidateSha,
    target,
    staticArtifact,
    compiledFunctions,
    runtimeConfiguration,
    migrations
  };
}

function parseEnvelope(value) {
  expectExactKeys(
    value,
    [
      "algorithm",
      "candidateSha",
      "compiledFunctions",
      "migrations",
      "runtimeConfiguration",
      "schemaVersion",
      "sealDigest",
      "staticArtifact",
      "target"
    ],
    "Release envelope"
  );
  if (value.schemaVersion !== 1 || value.algorithm !== "sha256") {
    throw new Error("Release envelope has an unsupported schema or algorithm");
  }
  if (typeof value.candidateSha !== "string" || !gitShaPattern.test(value.candidateSha)) {
    throw new Error("Release envelope has an invalid candidate SHA");
  }
  targetDefinition(value.target);
  if (typeof value.sealDigest !== "string" || !sha256Pattern.test(value.sealDigest)) {
    throw new Error("Release envelope has an invalid seal digest");
  }
  return value;
}

function digestEnvelope(unsigned) {
  return sha256(canonicalJson(unsigned));
}

function ensureEnvelopeIsPrivate(artifactDirectory, envelopePath) {
  const relativePath = path.relative(path.resolve(artifactDirectory), path.resolve(envelopePath));
  if (!relativePath.startsWith("..") && !path.isAbsolute(relativePath)) {
    throw new Error("Release envelope metadata must remain outside the public artifact directory");
  }
}

export function validatePagesTarget(projectName, domain) {
  if (projectName !== pagesProjectName) throw new Error(`Cloudflare Pages project must be ${pagesProjectName}`);
  if (domain !== pagesDomain) throw new Error(`Cloudflare Pages domain must be ${pagesDomain}`);
  return { projectName, domain };
}

export async function createReleaseEnvelope({ artifactDirectory, envelopePath, configPath, migrationsDirectory, target, candidateSha }) {
  if (typeof candidateSha !== "string" || !gitShaPattern.test(candidateSha)) {
    throw new Error("Release envelope candidate SHA must be a lowercase full Git SHA");
  }
  targetDefinition(target);
  ensureEnvelopeIsPrivate(artifactDirectory, envelopePath);
  if (!(await stat(path.resolve(artifactDirectory))).isDirectory()) throw new Error("Release artifact directory does not exist");

  const manifest = await verifyArtifactManifest(artifactDirectory, candidateSha, { quiet: true });
  const manifestContents = await readFile(path.join(artifactDirectory, artifactManifestFileName));
  const runtimeConfiguration = await readSealedRuntimeConfiguration({ configPath, target });
  const migrations = {
    directory: path.relative(path.dirname(configPath), migrationsDirectory).split(path.sep).join("/"),
    files: await readMigrations(migrationsDirectory)
  };
  const staticArtifact = {
    manifestFile: artifactManifestFileName,
    manifestSha256: sha256(manifestContents),
    fileCount: manifest.files.length
  };
  const compiledFunctions = await readCompiledFunctions(artifactDirectory, manifest);
  const unsigned = unsignedEnvelope({ candidateSha, target, staticArtifact, compiledFunctions, runtimeConfiguration, migrations });
  const envelope = { ...unsigned, sealDigest: digestEnvelope(unsigned) };

  await mkdir(path.dirname(path.resolve(envelopePath)), { recursive: true });
  await writeFile(envelopePath, `${JSON.stringify(envelope, null, 2)}\n`, "utf8");
  return envelope;
}

export async function verifyReleaseEnvelope({
  artifactDirectory,
  envelopePath,
  configPath,
  migrationsDirectory,
  target,
  candidateSha,
  expectedSealDigest
}) {
  if (typeof candidateSha !== "string" || !gitShaPattern.test(candidateSha)) {
    throw new Error("Release envelope candidate SHA must be a lowercase full Git SHA");
  }
  if (typeof expectedSealDigest !== "string" || !sha256Pattern.test(expectedSealDigest)) {
    throw new Error("Trusted release envelope digest is invalid");
  }
  let value;
  try {
    value = JSON.parse(await readFile(envelopePath, "utf8"));
  } catch (error) {
    if (error instanceof SyntaxError) throw new Error("Release envelope is not valid JSON");
    throw error;
  }
  const envelope = parseEnvelope(value);
  if (envelope.candidateSha !== candidateSha || envelope.target !== target) {
    throw new Error("Release envelope does not match the verified candidate and deployment target");
  }
  const unsigned = unsignedEnvelope(envelope);
  if (digestEnvelope(unsigned) !== envelope.sealDigest || envelope.sealDigest !== expectedSealDigest) {
    throw new Error("Release envelope does not match the trusted verification digest");
  }

  const manifest = await verifyArtifactManifest(artifactDirectory, candidateSha, { quiet: true });
  const manifestContents = await readFile(path.join(artifactDirectory, artifactManifestFileName));
  if (envelope.staticArtifact.manifestFile !== artifactManifestFileName ||
      envelope.staticArtifact.manifestSha256 !== sha256(manifestContents) ||
      envelope.staticArtifact.fileCount !== manifest.files.length) {
    throw new Error("Artifact manifest does not match the sealed release envelope");
  }

  const runtimeConfiguration = await readSealedRuntimeConfiguration({ configPath, target });
  if (canonicalJson(runtimeConfiguration) !== canonicalJson(envelope.runtimeConfiguration)) {
    throw new Error("Runtime configuration does not match the sealed release envelope");
  }
  const migrations = {
    directory: path.relative(path.dirname(configPath), migrationsDirectory).split(path.sep).join("/"),
    files: await readMigrations(migrationsDirectory)
  };
  if (canonicalJson(migrations) !== canonicalJson(envelope.migrations)) {
    throw new Error("Migrations do not match the sealed release envelope");
  }
  const compiledFunctions = await readCompiledFunctions(artifactDirectory, manifest);
  if (canonicalJson(compiledFunctions) !== canonicalJson(envelope.compiledFunctions)) {
    throw new Error("Compiled Functions do not match the sealed release envelope");
  }
  return envelope;
}

async function assertStagedDeploymentWorkspace(stageDirectory) {
  const expectedEntries = ["migrations", "out", releaseEnvelopeFileName, "wrangler.jsonc"];
  const entries = await readdir(stageDirectory, { withFileTypes: true });
  const names = entries.map((entry) => entry.name).sort();
  if (names.length !== expectedEntries.length || names.some((name, index) => name !== expectedEntries[index])) {
    throw new Error("Staged deployment workspace must contain only the sealed artifact, configuration, migrations, and envelope");
  }
  for (const entry of entries) {
    if (entry.isSymbolicLink()) throw new Error(`Staged deployment workspace cannot contain symlinks: ${entry.name}`);
  }
  if (!(await lstat(path.join(stageDirectory, "out"))).isDirectory() ||
      !(await lstat(path.join(stageDirectory, "migrations"))).isDirectory()) {
    throw new Error("Staged deployment workspace has invalid artifact or migration directories");
  }
  if ((await lstat(path.join(stageDirectory, "wrangler.jsonc"))).isDirectory() ||
      (await lstat(path.join(stageDirectory, releaseEnvelopeFileName))).isDirectory()) {
    throw new Error("Staged deployment workspace has invalid sealed metadata files");
  }
}

export async function stageReleaseDeployment({
  artifactDirectory,
  envelopePath,
  configPath,
  migrationsDirectory,
  target,
  candidateSha,
  expectedSealDigest,
  stageDirectory
}) {
  const resolvedStageDirectory = path.resolve(stageDirectory);
  const relativeStagePath = path.relative(path.resolve(artifactDirectory), resolvedStageDirectory);
  if (!relativeStagePath.startsWith("..") || path.isAbsolute(relativeStagePath)) {
    throw new Error("Staged deployment workspace must remain outside the public artifact directory");
  }
  if (await lstat(resolvedStageDirectory).catch(() => undefined)) {
    throw new Error("Staged deployment workspace already exists");
  }

  await verifyReleaseEnvelope({
    artifactDirectory,
    envelopePath,
    configPath,
    migrationsDirectory,
    target,
    candidateSha,
    expectedSealDigest
  });

  await mkdir(resolvedStageDirectory, { recursive: true });
  await Promise.all([
    cp(artifactDirectory, path.join(resolvedStageDirectory, "out"), { recursive: true, errorOnExist: true }),
    cp(migrationsDirectory, path.join(resolvedStageDirectory, "migrations"), { recursive: true, errorOnExist: true }),
    writeFile(path.join(resolvedStageDirectory, "wrangler.jsonc"), await readFile(configPath)),
    writeFile(path.join(resolvedStageDirectory, releaseEnvelopeFileName), await readFile(envelopePath))
  ]);
  await assertStagedDeploymentWorkspace(resolvedStageDirectory);
  const stagedEnvelope = await verifyReleaseEnvelope({
    artifactDirectory: path.join(resolvedStageDirectory, "out"),
    envelopePath: path.join(resolvedStageDirectory, releaseEnvelopeFileName),
    configPath: path.join(resolvedStageDirectory, "wrangler.jsonc"),
    migrationsDirectory: path.join(resolvedStageDirectory, "migrations"),
    target,
    candidateSha,
    expectedSealDigest
  });
  return { directory: resolvedStageDirectory, envelope: stagedEnvelope };
}

function projectPaths() {
  const projectRoot = path.resolve(import.meta.dirname, "..");
  return {
    configPath: path.join(projectRoot, "wrangler.jsonc"),
    migrationsDirectory: path.join(projectRoot, "migrations")
  };
}

async function runCli() {
  const [command, ...args] = process.argv.slice(2);
  const paths = projectPaths();
  if (command === "target" && args.length === 2) {
    validatePagesTarget(args[0], args[1]);
    return;
  }
  if (command === "create" && args.length === 4) {
    const envelope = await createReleaseEnvelope({
      artifactDirectory: args[0],
      envelopePath: args[1],
      target: args[2],
      candidateSha: args[3],
      ...paths
    });
    console.log(envelope.sealDigest);
    return;
  }
  if (command === "verify" && args.length === 5) {
    await verifyReleaseEnvelope({
      artifactDirectory: args[0],
      envelopePath: args[1],
      target: args[2],
      candidateSha: args[3],
      expectedSealDigest: args[4],
      ...paths
    });
    console.log("Verified the sealed release envelope.");
    return;
  }
  if (command === "stage" && args.length === 6) {
    await stageReleaseDeployment({
      artifactDirectory: args[0],
      envelopePath: args[1],
      target: args[2],
      candidateSha: args[3],
      expectedSealDigest: args[4],
      stageDirectory: args[5],
      ...paths
    });
    console.log("Staged the verified deployment workspace.");
    return;
  }
  throw new Error(
    "Usage: node scripts/releaseEnvelope.mjs target <pages-project> <pages-domain> | create <artifact-directory> <envelope-path> <production|preview> <candidate-sha> | verify <artifact-directory> <envelope-path> <production|preview> <candidate-sha> <trusted-seal-digest> | stage <artifact-directory> <envelope-path> <production|preview> <candidate-sha> <trusted-seal-digest> <stage-directory>"
  );
}

const isDirectExecution = Boolean(process.argv[1]) && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);

if (isDirectExecution) {
  runCli().catch((error) => {
    console.error(error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
  });
}
