import { cp, mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { createArtifactManifest } from "./artifactIntegrity.mjs";
import {
  createReleaseEnvelope,
  pagesDomain,
  pagesProjectName,
  releaseEnvelopeFileName,
  stageReleaseDeployment,
  validatePagesTarget,
  verifyReleaseEnvelope
} from "./releaseEnvelope.mjs";

const projectRoot = path.resolve(import.meta.dirname, "..");
const candidateSha = "a".repeat(40);
const contentHash = "b".repeat(64);
const routes = {
  version: 1,
  description: "Generated by wrangler@4.131.0",
  include: ["/api/contact", "/api/contact/verify"],
  exclude: []
};

async function createFixture() {
  const rootDirectory = await mkdtemp(path.join(os.tmpdir(), "portfolio-release-envelope-"));
  const artifactDirectory = path.join(rootDirectory, "out");
  const envelopePath = path.join(rootDirectory, "release-envelope", releaseEnvelopeFileName);
  const configPath = path.join(rootDirectory, "wrangler.jsonc");
  const migrationsDirectory = path.join(rootDirectory, "migrations");
  await mkdir(path.join(artifactDirectory, "_worker.js"), { recursive: true });
  await cp(path.join(projectRoot, "migrations"), migrationsDirectory, { recursive: true });
  await writeFile(configPath, await readFile(path.join(projectRoot, "wrangler.jsonc"), "utf8"), "utf8");
  await Promise.all([
    writeFile(path.join(artifactDirectory, "index.html"), "<!doctype html><title>sealed artifact</title>", "utf8"),
    writeFile(path.join(artifactDirectory, "_worker.js", "index.js"), "export default { fetch() { return new Response('ok'); } };", "utf8"),
    writeFile(path.join(artifactDirectory, "_routes.json"), `${JSON.stringify(routes, null, 2)}\n`, "utf8"),
    writeFile(
      path.join(artifactDirectory, "content-version.json"),
      `${JSON.stringify({
        schemaVersion: 1,
        contentHash,
        commitSha: candidateSha,
        generatedAt: "2026-10-08T00:00:00.000Z",
        deployedAt: "2026-10-08T00:00:01.000Z"
      })}\n`,
      "utf8"
    )
  ]);
  await createArtifactManifest(artifactDirectory);
  const envelope = await createReleaseEnvelope({
    artifactDirectory,
    envelopePath,
    configPath,
    migrationsDirectory,
    target: "production",
    candidateSha
  });
  return { rootDirectory, artifactDirectory, envelopePath, configPath, migrationsDirectory, envelope };
}

async function verifyFixture(fixture, options = {}) {
  return verifyReleaseEnvelope({
    artifactDirectory: fixture.artifactDirectory,
    envelopePath: fixture.envelopePath,
    configPath: fixture.configPath,
    migrationsDirectory: fixture.migrationsDirectory,
    target: "production",
    candidateSha,
    expectedSealDigest: fixture.envelope.sealDigest,
    ...options
  });
}

async function withFixture(callback) {
  const fixture = await createFixture();
  try {
    await callback(fixture);
  } finally {
    await rm(fixture.rootDirectory, { recursive: true, force: true });
  }
}

describe("release envelope", () => {
  it("seals the static manifest, compiled Worker, target configuration, and migrations outside the public artifact", async () => {
    await withFixture(async (fixture) => {
      expect(fixture.envelope.target).toBe("production");
      expect(fixture.envelope.runtimeConfiguration.pages).toEqual({
        projectName: pagesProjectName,
        domain: pagesDomain,
        branch: "main"
      });
      expect(fixture.envelope.compiledFunctions.files.map((file) => file.path)).toEqual(["_worker.js/index.js"]);
      expect(path.relative(fixture.artifactDirectory, fixture.envelopePath).startsWith("..")).toBe(true);
      await expect(verifyFixture(fixture)).resolves.toMatchObject({ sealDigest: fixture.envelope.sealDigest });
    });
  });

  it("rejects altered static files and a replacement manifest even when it matches those altered files", async () => {
    await withFixture(async (fixture) => {
      await writeFile(path.join(fixture.artifactDirectory, "index.html"), "tampered static output", "utf8");
      await expect(verifyFixture(fixture)).rejects.toThrow(/integrity verification failed/);

      await createArtifactManifest(fixture.artifactDirectory);
      await expect(verifyFixture(fixture)).rejects.toThrow(/Artifact manifest does not match the sealed release envelope/);
    });
  });

  it("rejects a modified compiled Worker even if a matching static manifest is substituted", async () => {
    await withFixture(async (fixture) => {
      await writeFile(path.join(fixture.artifactDirectory, "_worker.js", "index.js"), "export default {};", "utf8");
      await createArtifactManifest(fixture.artifactDirectory);

      await expect(verifyFixture(fixture)).rejects.toThrow(/Artifact manifest does not match the sealed release envelope/);
    });
  });

  it("rejects altered runtime configuration, migration bytes, and the wrong deployment environment", async () => {
    await withFixture(async (fixture) => {
      const config = JSON.parse(await readFile(fixture.configPath, "utf8"));
      config.vars.CONTACT_ALLOWED_ORIGINS = "https://unreviewed.example";
      await writeFile(fixture.configPath, `${JSON.stringify(config, null, 2)}\n`, "utf8");
      await expect(verifyFixture(fixture)).rejects.toThrow(/CONTACT_ALLOWED_ORIGINS/);

      await writeFile(fixture.configPath, await readFile(path.join(projectRoot, "wrangler.jsonc"), "utf8"), "utf8");
      await writeFile(
        path.join(fixture.migrationsDirectory, "0002_contact_payload_fingerprint.sql"),
        "ALTER TABLE contact_rate_reservations ADD COLUMN payload_hash TEXT; -- altered\n",
        "utf8"
      );
      await expect(verifyFixture(fixture)).rejects.toThrow(/Migrations do not match/);
      await expect(verifyFixture(fixture, { target: "preview" })).rejects.toThrow(/candidate and deployment target/);
    });
  });

  it("rejects unreviewed Pages project and domain values before a release is sealed", () => {
    expect(validatePagesTarget(pagesProjectName, pagesDomain)).toEqual({ projectName: pagesProjectName, domain: pagesDomain });
    expect(() => validatePagesTarget("other-project", pagesDomain)).toThrow(/Pages project/);
    expect(() => validatePagesTarget(pagesProjectName, "derived.pages.dev")).toThrow(/Pages domain/);
  });

  it("stages only verified deployment inputs without a source Functions tree", async () => {
    await withFixture(async (fixture) => {
      const stageDirectory = path.join(fixture.rootDirectory, "release-deployment");
      await expect(
        stageReleaseDeployment({
          artifactDirectory: fixture.artifactDirectory,
          envelopePath: fixture.envelopePath,
          configPath: fixture.configPath,
          migrationsDirectory: fixture.migrationsDirectory,
          target: "production",
          candidateSha,
          expectedSealDigest: fixture.envelope.sealDigest,
          stageDirectory
        })
      ).resolves.toMatchObject({ directory: stageDirectory });
      await expect(readFile(path.join(stageDirectory, "wrangler.jsonc"), "utf8")).resolves.toBe(
        await readFile(fixture.configPath, "utf8")
      );
      await expect(readFile(path.join(stageDirectory, "out", "_worker.js", "index.js"), "utf8")).resolves.toContain(
        "export default"
      );
      await expect(readFile(path.join(stageDirectory, "functions"), "utf8")).rejects.toThrow();
    });
  });
});
