import { writeFile, rename, unlink } from "node:fs/promises";
import { fileURLToPath } from "node:url";

export const contactTldSource = "https://data.iana.org/TLD/tlds-alpha-by-domain.txt";
const maxBytes = 131_072;
const destination = new URL("../src/lib/contact/ianaTlds.ts", import.meta.url);

export function parseContactTlds(text) {
  const [header, ...lines] = text.trim().split(/\r?\n/);
  const version = /^# Version (\d{10}), Last Updated .+$/.exec(header ?? "")?.[1];
  if (!version || lines.length < 1_000 || lines.length > 10_000) throw new Error("Invalid IANA TLD snapshot envelope.");
  if (lines.some((line) => !/^(?:[A-Z]{2,63}|XN--[A-Z0-9-]{2,59})$/.test(line))) {
    throw new Error("Invalid IANA TLD entry.");
  }
  const tlds = lines.map((line) => line.toLowerCase());
  if (new Set(tlds).size !== tlds.length || [...tlds].sort().join("\n") !== tlds.join("\n")) {
    throw new Error("IANA TLD entries must be unique and sorted.");
  }
  if (!["com", "org", "gov", "edu", "co", "dev", "xn--p1ai"].every((tld) => tlds.includes(tld))) {
    throw new Error("IANA TLD snapshot is missing established domains.");
  }
  return { version, tlds };
}

export async function downloadContactTlds(fetcher = fetch) {
  const response = await fetcher(contactTldSource, { redirect: "error", signal: AbortSignal.timeout(10_000) });
  if (!response.ok || !response.body) throw new Error("IANA TLD download failed.");
  const length = response.headers.get("Content-Length");
  if (length && (!/^\d+$/.test(length) || Number(length) > maxBytes)) {
    void response.body.cancel().catch(() => undefined);
    throw new Error("IANA TLD snapshot exceeds the download limit.");
  }
  const reader = response.body.getReader();
  const chunks = [];
  let total = 0;
  let complete = false;
  try {
    while (true) {
      const { done, value } = await reader.read();
      if (done) { complete = true; break; }
      total += value.byteLength;
      if (total > maxBytes) throw new Error("IANA TLD snapshot exceeds the download limit.");
      chunks.push(value);
    }
    return parseContactTlds(new TextDecoder("utf-8", { fatal: true }).decode(Buffer.concat(chunks)));
  } finally {
    if (!complete) void reader.cancel().catch(() => undefined);
  }
}

async function updateContactTlds() {
  const { version, tlds } = await downloadContactTlds();
  const source = `// Generated by npm run update:contact-tlds. Review the source/version and diff.\n` +
    `export const contactTldSnapshot = ${JSON.stringify({ source: contactTldSource, version }, null, 2)} as const;\n\n` +
    `export const contactTopLevelDomains: ReadonlySet<string> = new Set(\n\`${tlds.join("\n")}\`.split("\\n")\n);\n`;
  const temporary = new URL(`${destination.href}.tmp`);
  let ownsTemporary = false;
  try {
    await writeFile(temporary, source, { encoding: "utf8", flag: "wx" });
    ownsTemporary = true;
    await rename(temporary, destination);
  } finally {
    if (ownsTemporary) await unlink(temporary).catch((error) => { if (error.code !== "ENOENT") throw error; });
  }
  process.stdout.write(`Updated ${tlds.length} contact TLDs from IANA version ${version}.\n`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) await updateContactTlds();
