import type { Metadata } from "next";
import { LegalDocument, resolveLegalContactEmail, resolveLegalEffectiveDate } from "@/components/legal/LegalDocument";
import { SmartLink } from "@/components/navigation/SmartLink";
import { createPageMetadata } from "@/lib/content/createPageMetadata";
import { getPortfolioContent } from "@/lib/content/getPortfolioContent";
import { routeHeaderContent } from "@/lib/content/routeHeaderContent";
import { siteRoutes } from "@/lib/routing/siteRoutes";

const contactTermsHeader = routeHeaderContent[siteRoutes.contactTerms];
const pageTitle = contactTermsHeader.title;
const pageDescription = "Conditions for contact requests, replies, communication costs, and responsible use.";
const contactTermsEffectiveDate = resolveLegalEffectiveDate("2026-09-13");

export function generateMetadata(): Metadata {
  return createPageMetadata(getPortfolioContent(), {
    pathname: siteRoutes.contactTerms,
    title: pageTitle,
    description: pageDescription
  });
}

export default function ContactTermsPage() {
  const content = getPortfolioContent();
  const contactEmail = resolveLegalContactEmail(content.siteSettings.legalContactEmail);

  return (
    <LegalDocument
      description={contactTermsHeader.description}
      eyebrow={contactTermsHeader.eyebrow}
      effectiveDate={contactTermsEffectiveDate}
      motionEnabled={content.siteSettings.enableScrollMotion}
      title={pageTitle}
    >
      <section>
        <h2>Scope and agreement</h2>
        <p>
          These Terms explain the conditions for using this portfolio&apos;s <SmartLink href={siteRoutes.contact}>contact form</SmartLink>{" "}
          and the permission requested for communications about your inquiry. Nicolas Gioanni operates this personal portfolio.
          Read these Terms together with the <SmartLink href={siteRoutes.terms}>Site Terms &amp; Accuracy Notice</SmartLink> and{" "}
          <SmartLink href={siteRoutes.privacy}>Privacy Notice</SmartLink>. The Privacy Notice describes personal-information
          processing; these Terms do not replace it or authorize unrelated uses of your information.
        </p>
        <p>
          By selecting the contact acknowledgment and sending the form, you agree to these Terms and request the communications
          described below. A direct email is an alternative contact method; it does not mean that you checked the form&apos;s boxes
          or gave permission for an additional channel. These Terms do not override a separate written agreement that expressly
          applies to a particular engagement.
        </p>
      </section>

      <section>
        <h2>Your contact details and authority</h2>
        <p>
          Provide accurate information and an email address you control or are authorized to use. If you provide a phone number,
          you confirm that you are its current subscriber or authorized user and may receive inquiry-related calls and texts
          there. Do not submit another person&apos;s details to cause unwanted contact or impersonate another person or organization.
        </p>
        <p>
          Tell Nicolas promptly if an address or number is incorrect, reassigned, shared in a way that affects your permission,
          or no longer available to you. You must have the legal capacity and authority needed to make the inquiry; where an
          authorized adult is required, ask that adult to make contact. This professional contact channel is not intended to
          collect children&apos;s personal information.
        </p>
      </section>

      <section>
        <h2>What communication you request</h2>
        <p>
          Submitting an eligible form requests an automated email confirmation and permits email replies and reasonable follow-up
          about the inquiry, including clarification, scheduling, corrections, or closing the conversation. A confirmation is
          generated by the delivery system; personal responses are handled separately. Frequency depends on the inquiry, with no
          fixed schedule or continuing messaging subscription.
        </p>
        <p>
          Providing a phone number is optional. If you include one, you also permit Nicolas to respond about that inquiry by a
          manually placed call or a personally composed text. Leave the phone field blank if you want email communication only,
          and state any channel or timing preference in your message. Supplying a number does not require Nicolas to use it.
        </p>
        <p>
          This acknowledgment does not authorize marketing campaigns, unrelated promotional messages, automated or prerecorded
          calls, or automated text campaigns. It does not give another organization permission to market to you and does not
          authorize recording a call. Any materially different communication purpose requires whatever separate permission or
          notice applicable law requires.
        </p>
      </section>

      <section>
        <h2>Carrier, messaging, and connection charges</h2>
        <p>
          Nicolas does not charge a fee to submit this form or receive an inquiry response, and this is not a paid messaging
          service. Your carrier, internet provider, email provider, or messaging service may charge for calls, texts, data,
          roaming, or international use, including messages you send to correct information or stop contact. Charges depend on
          your own plan and provider; check them before supplying a number or responding.
        </p>
        <p>
          You are responsible for charges assessed under your own provider agreement to the extent permitted by law. Nicolas does
          not set those rates or promise reimbursement of ordinary provider charges. Choosing email only may avoid phone or text
          charges, but internet or data charges may still apply. This provision does not shift responsibility for charges caused
          by conduct for which Nicolas is legally responsible.
        </p>
      </section>

      <section>
        <h2>Change your preferences or stop replies</h2>
        <p>
          You may withdraw permission for future optional contact at any time. Reply to a genuine message, tell Nicolas during a
          call, or email <SmartLink href={`mailto:${contactEmail}`}>{contactEmail}</SmartLink>. For a genuine two-way text, you
          may reply STOP or simply say that you do not want further texts. No special wording is required, and no fee is charged
          by Nicolas to process the request. Specify a channel if you want only that channel stopped; otherwise a clear request to
          stop contact will be treated as applying to optional follow-up across channels.
        </p>
        <p>
          Requests are handled personally, not by an automated STOP service. Nicolas will honor a clear request promptly and
          within any applicable legal deadline. Messages already sent or in transit may still arrive. Limited communications
          necessary to acknowledge the request, address a legal obligation, or resolve a security issue may still be sent where
          permitted by law; this is not permission to continue the original conversation after you ask it to stop. Withdrawing
          contact permission does not automatically erase records; see the <SmartLink href={siteRoutes.privacy}>Privacy Notice</SmartLink>{" "}
          for deletion requests and retention.
        </p>
      </section>

      <section>
        <h2>Delivery, responses, and reliance</h2>
        <p>
          The form&apos;s success screen and automated email report submission processing; they do not prove that a person has read
          the request, that every receiving system has delivered it, or that a response or proposed opportunity has been accepted.
          A receipt may arrive before the separate owner notification is successfully delivered. Delivery systems, spam filters,
          blocked senders, unavailable accounts, network problems, or incorrect details may delay or prevent communication.
        </p>
        <p>
          Any statement of an intention to respond is a best-effort intention, not a guaranteed response time or service-level
          commitment. Nicolas may decline an inquiry or end a conversation, subject to applicable legal duties. Do not rely on
          this channel for an application deadline, legal notice, urgent operational decision, or other time-sensitive requirement
          unless a separate arrangement expressly accepts that use. Use the form&apos;s offered retry or direct email alternative when
          needed; repeated new submissions may create unnecessary messages and consume submission limits.
        </p>
      </section>

      <section>
        <h2>Professional context and urgent matters</h2>
        <p>
          An inquiry or reply does not itself create an employment, consulting, advisory, fiduciary, agency, confidential, or
          other professional engagement, an offer of work, or a commitment to provide services. Any engagement, deliverable,
          payment, or special duty requires a separate agreement. Communications are in Nicolas&apos;s individual capacity unless he
          expressly identifies an authorized role; listed employers, universities, collaborators, and other organizations are not
          made parties to your inquiry by appearing on the portfolio.
        </p>
        <p>
          This channel is not an emergency service, crisis service, medical advice line, or continuously monitored support desk.
          For an emergency, use the appropriate local emergency service. Security reports should follow the{" "}
          <SmartLink href={siteRoutes.security}>Security &amp; Responsible Disclosure Notice</SmartLink>; submitting a report does
          not authorize testing, accessing systems, or exceeding the permissions stated there.
        </p>
      </section>

      <section>
        <h2>Legitimate and lawful use</h2>
        <p>
          Use the channel for genuine inquiries. Do not send spam, bulk solicitations, deceptive promotions, harassment, threats,
          discriminatory abuse, impersonation, unlawful content, malicious links or code, stolen material, or information you
          have no right to share. Do not use it to trigger messages to unwilling recipients, scrape contact details, test stolen
          credentials, distribute malware, or evade verification, rate limits, delivery safeguards, or other access restrictions.
        </p>
        <p>
          Reasonable verification, filtering, validation, rate limits, blocking, and other protective measures may reject or
          delay a legitimate request as well as abusive traffic. Nicolas may disregard or restrict misuse and preserve or report
          relevant information where lawful and appropriate, consistently with the <SmartLink href={siteRoutes.privacy}>Privacy Notice</SmartLink>.
          These restrictions do not prevent good-faith complaints, lawful criticism, protected reporting, or exercising legal rights.
        </p>
      </section>

      <section>
        <h2>Sensitive information, confidentiality, and submitted material</h2>
        <p>
          Send only what is reasonably needed for the inquiry. Do not include passwords, authentication codes, private keys,
          access tokens, payment-card or banking details, government identifiers, medical records, children&apos;s personal
          information, trade secrets, restricted employer or client information, or unnecessary information about another person.
          Arrange an appropriate channel and any needed confidentiality agreement before sharing sensitive material.
        </p>
        <p>
          Submitting a message or marking it confidential does not by itself establish an NDA, legal privilege, or a special
          confidential relationship. Ordinary email and text may be accessible to service providers, shared-account users, device
          users, or other recipients outside Nicolas&apos;s control; no communication method is guaranteed completely secure. This
          does not remove duties that apply under law or an existing agreement.
        </p>
        <p>
          You retain your rights in material you submit. You authorize only the handling reasonably needed to receive, assess,
          respond to, and appropriately retain the inquiry as described in the <SmartLink href={siteRoutes.privacy}>Privacy Notice</SmartLink>;
          submitting it does not grant a general right to publish it, transfer its ownership, or use it in unrelated marketing. Do
          not send material subject to incompatible third-party restrictions.
        </p>
      </section>

      <section>
        <h2>Privacy, providers, and mistaken messages</h2>
        <p>
          The <SmartLink href={siteRoutes.privacy}>Privacy Notice</SmartLink> explains verification, submission processing, email
          delivery, service providers, retention, and rights requests. Contact information is not sold or rented by the portfolio
          owner or used for unrelated marketing. Acknowledging these Terms is not a waiver of privacy rights or blanket consent to
          every possible use of your information.
        </p>
        <p>
          If you receive a message because someone entered your details without permission, you did not thereby agree to these
          Terms or authorize future contact. Use the contact address published on this website to report it and ask for optional
          follow-up to stop. Include only the minimum information needed to identify the mistaken message; do not forward passwords
          or other sensitive material.
        </p>
      </section>

      <section>
        <h2>Impersonation and suspicious communications</h2>
        <p>
          A familiar display name, phone number, logo, or quoted message does not prove that a message is genuine. If a
          communication unexpectedly asks for money, credentials, authentication codes, remote access, or sensitive information,
          verify it independently using the contact information on this website before acting. Do not rely solely on a link or
          reply address in a suspicious message. Report suspected impersonation through{" "}
          <SmartLink href={`mailto:${contactEmail}`}>{contactEmail}</SmartLink>; use the{" "}
          <SmartLink href={siteRoutes.security}>Security &amp; Responsible Disclosure Notice</SmartLink> for a technical security issue.
        </p>
      </section>

      <section>
        <h2>Availability and limits of responsibility</h2>
        <p>
          The contact channel is provided as available. To the extent allowed by applicable law, no warranty is given that it will
          be uninterrupted, error-free, secure in every circumstance, or suitable for a particular purpose. Nicolas is not
          responsible for losses caused solely by your inaccurate details, unauthorized submissions by others, your provider&apos;s
          ordinary charges, or third-party failures beyond his reasonable control, except where applicable law imposes responsibility.
        </p>
        <p>
          To the extent permitted by applicable law, Nicolas is not liable for indirect, incidental, special, or consequential
          losses from using or being unable to use this contact channel, such as lost opportunities, lost profits, or interruption
          of business. This limitation concerns the contact channel and does not override duties expressly accepted in a separate
          agreement.
        </p>
        <p>
          Nothing in these Terms excludes or limits liability for fraud, fraudulent misrepresentation, willful misconduct, gross
          negligence, or any liability that cannot legally be excluded or limited. Nothing waives mandatory consumer, privacy,
          communications, or other statutory rights, prevents a lawful complaint or report, or makes you responsible for Nicolas&apos;s
          own unlawful conduct. If a limitation is not permitted where it applies, it operates only to the extent legally permitted;
          the remaining lawful provisions continue to apply.
        </p>
      </section>

      <section>
        <h2>Updates and questions</h2>
        <p>
          Updates will be posted with a revised effective date and apply prospectively. A later revision does not retroactively
          broaden permission you already gave, waive an existing claim, or authorize a new channel or purpose without any legally
          required notice or permission. A failure to enforce one provision on one occasion does not waive it on another occasion.
        </p>
        <p>
          For a question about these Terms, a correction, a communication preference, an unwanted message, or an accessible
          alternative to the form, contact Nicolas Gioanni at <SmartLink href={`mailto:${contactEmail}`}>{contactEmail}</SmartLink>.
          The contact form remains available at <SmartLink href={siteRoutes.contact}>{siteRoutes.contact}</SmartLink>.
        </p>
      </section>
    </LegalDocument>
  );
}
